### ISSUE TITLE
[netlify-cms-widget-mdx] Broken compatibility with latest netlify-cms-app

### ISSUE THREAD

**Issue by erikdstock** [buz-zard/gatsby-mdx#40]
I'm not sure of the best place to report this, but a recent change to [`netlify-cms-widget-markdown`](https://github.com/netlify/netlify-cms/pull/2141) changed its export name from `MarkdownControl` to `controlComponent`. For those using netlify-cms > 2.6.2, this seems to break the markdown/mdx widget setup. Complicating matters the upgrade in netlify-cms was necessary due to another issue in gatsbyjs/gatsby#12776.

Again, not sure which is the best place to bring this up, but any advice would be appreciated. I tried a simple change of the import in the package locally but this just led to another error.

**Comment by buz-zard** [comment]
Thanks Erik for the informative issue. Should be fixed with [0.4.0](https://www.npmjs.com/package/netlify-cms-widget-mdx/v/0.4.0)
